// Alle spelinhoud van ForeverChoser.
// Stand van het onderzoek: 9 oktober 2026 (WoW Forever beta, launch 4 november 2026).
// Waarden van racials en class-wijzigingen komen uit beta- en pre-launchbronnen
// en kunnen nog veranderen. Zie SOURCES onderaan.

export const RESEARCH_DATE = '9 oktober 2026';
export const LAUNCH_DATE = '4 november 2026';

export const TRAITS = {
  melee: { label: 'Gevecht van dichtbij', icon: '⚔️' },
  ranged: { label: 'Afstand', icon: '🎯' },
  magic: { label: 'Magie', icon: '✨' },
  physical: { label: 'Wapens & spierkracht', icon: '💪' },
  pet: { label: 'Een metgezel', icon: '🐺' },
  stealth: { label: 'Sluipen', icon: '🌑' },
  heal: { label: 'Genezen', icon: '💚' },
  tank: { label: 'Beschermen', icon: '🛡️' },
  burst: { label: 'Grote klappen', icon: '💥' },
  control: { label: 'Controle', icon: '🧊' },
  complex: { label: 'Veel knoppen', icon: '🎹' },
  simple: { label: 'Rustig spelen', icon: '🍵' },
  solo: { label: 'Solo-avontuur', icon: '🧭' },
  hybrid: { label: 'Veelzijdigheid', icon: '🔄' },
  dark: { label: 'Duisternis', icon: '🌒' },
  light: { label: 'Heilig licht', icon: '☀️' },
  nature: { label: 'Natuur & elementen', icon: '🌿' },
  shapeshift: { label: 'Gedaanteverwisseling', icon: '🐻' },
};

export const ROLES = {
  tank: { label: 'Tank', icon: '🛡️' },
  heal: { label: 'Healer', icon: '💚' },
  melee: { label: 'Melee DPS', icon: '⚔️' },
  ranged: { label: 'Ranged DPS', icon: '🎯' },
};

export const CLASSES = [
  {
    id: 'warrior',
    name: 'Warrior',
    abbr: 'War',
    icon: '⚔️',
    color: '#C69B6D',
    roles: ['tank', 'melee'],
    specs: ['Arms', 'Fury', 'Protection'],
    resource: 'Rage',
    armor: 'Mail, Plate vanaf level 40',
    difficulty: 4,
    soloEase: 2,
    tagline: 'Staal, woede en altijd als eerste de frontlinie in.',
    fantasy:
      'De Warrior bouwt Rage op door klappen uit te delen én te incasseren. Als Protection ben je de klassieke tank, als Arms of Fury een vernietigende melee-DPS. Heel sterk met goede uitrusting, maar meer dan andere classes afhankelijk van gear en een healer.',
    pros: [
      'Altijd gewild als tank in dungeons en raids',
      'Schaalt enorm met betere uitrusting',
      'Directe, fysieke speelstijl zonder franje',
    ],
    cons: [
      'Solo levelen is relatief traag en kwetsbaar',
      'Leunt op gear en healers',
      'Rage-beheer vraagt oefening',
    ],
    forever: [
      'Tactical Mastery wordt baseline vanaf level 14',
      'Victory Rush leer je op level 20, prettig bij solo levelen',
      'Improved Battle Shout is geen talent meer maar baseline',
    ],
    traits: { melee: 3, physical: 3, tank: 3, burst: 2, complex: 2, solo: 1, hybrid: 1 },
    duel: [
      'Je stormt als eerste een groep vijanden in, schild omhoog.',
      'Elke klap die je incasseert maakt je bozer en sterker.',
      'Eén perfect getimede genadeslag beslist het gevecht.',
      'Je draagt de zwaarste wapenrusting die er te vinden is.',
    ],
  },
  {
    id: 'paladin',
    name: 'Paladin',
    abbr: 'Pal',
    icon: '🔨',
    color: '#F48CBA',
    roles: ['tank', 'heal', 'melee'],
    specs: ['Holy', 'Protection', 'Retribution'],
    resource: 'Mana',
    armor: 'Mail, Plate vanaf level 40',
    difficulty: 2,
    soloEase: 3,
    tagline: 'Heilig Licht in een harnas van plaat.',
    fantasy:
      'Een heilige strijder die kan tanken (Protection), genezen (Holy) of met een tweehandig wapen kan toeslaan (Retribution). In Forever krijgt de Paladin een van de grootste opknapbeurten van alle classes, en voor het eerst kan ook de Horde een Paladin spelen, via de Undead.',
    pros: [
      'Erg stevig: je gaat niet snel dood',
      'Kan alle drie de rollen: tank, heal en DPS',
      'Sterke groepsbuffs (Blessings en Auras)',
    ],
    cons: [
      'Solo levelen is veilig, maar niet het snelst',
      'Weinig afstandsaanvallen: vijanden moeten naar jou toe',
      'Nog veel beta-tuning na de grote rework',
    ],
    forever: [
      'Protection krijgt een taunt via Seal of Fury en Judgment',
      'Consecration wordt baseline vanaf level 20',
      'Judgment verbruikt je actieve Seal niet meer',
      'Nieuwe aanval Holy Strike vanaf level 6',
      'Blessing of Kings is baseline in plaats van een talent',
      'Nieuw: Undead Paladin voor de Horde',
    ],
    traits: { melee: 2, light: 3, heal: 2, tank: 2, physical: 1, hybrid: 3, simple: 2, solo: 2 },
    duel: [
      'Je zegent je bondgenoten en laat heilig vuur op je vijanden neerdalen.',
      'Je bent een wandelend fort dat zichzelf ook nog kan genezen.',
      'Je roept een schild van Licht op dat je even onkwetsbaar maakt.',
      'Je bent ridder, genezer en beschermer tegelijk.',
    ],
  },
  {
    id: 'hunter',
    name: 'Hunter',
    abbr: 'Hun',
    icon: '🏹',
    color: '#AAD372',
    roles: ['ranged', 'melee'],
    specs: ['Beast Mastery', 'Marksmanship', 'Survival'],
    resource: 'Mana',
    armor: 'Leather, Mail vanaf level 40',
    difficulty: 2,
    soloEase: 5,
    tagline: 'Boog, beest en de wildernis.',
    fantasy:
      'De Hunter vecht op afstand met boog of geweer, samen met een getemd dier dat de klappen opvangt. Volgens vrijwel alle gidsen de makkelijkste class om solo te levelen. Icy Veins noemt in Forever ook een melee-DPS optie.',
    pros: [
      'Topkeuze voor solo levelen: je pet tankt voor je',
      'Veel afstand en controle met traps en kiten',
      'Tientallen soorten dieren om te temmen',
    ],
    cons: [
      'Vaak de populairste class: meer concurrentie om loot',
      'Je pet verzorgen (voeren, gedrag) is extra werk',
      'In groepen vraagt pet-aggro goede discipline',
    ],
    forever: [
      'Aimed Shot is baseline vanaf level 20',
      'Traps zijn ook in combat te gebruiken',
      'Nieuw: Human Hunter',
    ],
    traits: { ranged: 3, pet: 3, physical: 2, solo: 3, nature: 2, simple: 2, control: 1, burst: 1 },
    duel: [
      'Je trouwe wolf vecht zij aan zij met jou.',
      'Je raakt een doel op honderd meter met één pijl.',
      'Je zet vallen en lokt je prooi erin.',
      'Je trekt door de wildernis en temt de zeldzaamste beesten.',
    ],
  },
  {
    id: 'rogue',
    name: 'Rogue',
    abbr: 'Rog',
    icon: '🗡️',
    color: '#FFF468',
    roles: ['melee'],
    specs: ['Assassination', 'Combat', 'Subtlety'],
    resource: 'Energy en combo points',
    armor: 'Leather',
    difficulty: 3,
    soloEase: 3,
    tagline: 'Uit de schaduw, recht door het hart.',
    fantasy:
      'De Rogue sluipt onzichtbaar rond, opent met een verrassingsaanval en zet vijanden vast met stuns. Combo points opbouwen en uitgeven geeft een snel, actief ritme. Sterk in PvP en een pure melee-DPS in groepen.',
    pros: [
      'Stealth: jij kiest wanneer het gevecht begint',
      'Veel controle: stuns, Sap en Blind',
      'Gif maken, sloten openen en zakkenrollen',
    ],
    cons: [
      'Alleen melee-DPS: geen tank- of healrol',
      'Vraagt goede timing en veel knoppen',
      'Een slechte opening kan je duur komen te staan',
    ],
    forever: [
      'Krijgt net als elke class nieuwe talenten en een extra 16-punts mijlpaal per talentboom',
      'Dual spec vanaf level 40 (geldt voor alle classes)',
    ],
    traits: { melee: 3, stealth: 3, burst: 2, physical: 2, complex: 2, control: 1, dark: 1, solo: 1 },
    duel: [
      'Je verdwijnt in de schaduw en niemand ziet je komen.',
      'Je opent het gevecht met een verwoestende verrassingsaanval.',
      'Je smeert gif op je dolken voordat het gevecht begint.',
      'Je steelt de beurs van een wachter zonder dat hij het merkt.',
    ],
  },
  {
    id: 'priest',
    name: 'Priest',
    abbr: 'Pri',
    icon: '✨',
    color: '#F2F2F2',
    roles: ['heal', 'ranged'],
    specs: ['Discipline', 'Holy', 'Shadow'],
    resource: 'Mana',
    armor: 'Cloth',
    difficulty: 3,
    soloEase: 3,
    tagline: 'Licht en schaduw in één gewaad.',
    fantasy:
      'De Priest is de klassieke healer (Holy en Discipline), maar kan ook kiezen voor Shadow: een duistere caster met DoTs en geestmagie. Altijd welkom in groepen.',
    pros: [
      'Een van de meest gevraagde healers',
      'Shadow is een sterke solo-optie',
      'Krachtige hulpmiddelen zoals Power Word: Shield en Psychic Scream',
    ],
    cons: [
      'Kwetsbaar in cloth als je wordt aangevallen',
      'Levelen als Holy of Discipline is traag',
      'In raids vaak vooral healen',
    ],
    forever: [
      'Divine Spirit is geen talent meer maar baseline',
      'Nieuw: Gnome Priest',
    ],
    traits: { heal: 3, magic: 3, light: 2, dark: 2, ranged: 2, control: 1, solo: 1 },
    duel: [
      'Je redt een stervende bondgenoot op het allerlaatste moment.',
      'Je vult de geest van je vijand met angst en waanzin.',
      'Je zet een schild van licht om een vriend heen.',
      'Je bent het hart van elke groep: zonder jou geen overwinning.',
    ],
  },
  {
    id: 'shaman',
    name: 'Shaman',
    abbr: 'Sha',
    icon: '⚡',
    color: '#0070DD',
    text: '#5AA9FF',
    roles: ['heal', 'melee', 'ranged'],
    specs: ['Elemental', 'Enhancement', 'Restoration'],
    resource: 'Mana',
    armor: 'Leather, Mail vanaf level 40',
    difficulty: 3,
    soloEase: 3,
    tagline: 'De stem van vuur, aarde, water en lucht.',
    fantasy:
      'De Shaman roept de elementen aan via totems. Een echte hybride: Elemental (caster), Enhancement (melee) of Restoration (healer). In Forever voor het eerst ook speelbaar voor de Alliance, via de Dwarf.',
    pros: [
      'Drie heel verschillende speelstijlen in één class',
      'Totems maken je hele groep sterker',
      'Zelf-heals maken solo spelen prettig',
    ],
    cons: [
      'Totems plaatsen en beheren vraagt aandacht',
      'Mana-beheer is belangrijk',
      'Hybride: je verzamelt gear voor meerdere rollen',
    ],
    forever: [
      'Totem twisting is verwijderd om de class toegankelijker te maken',
      'Totems kun je terugroepen voor een deel van de mana of verplaatsen zonder opnieuw te casten',
      'Nieuw talent Maelstrom Weapon: Lightning Bolt tussen je melee-aanvallen door',
      'Nieuw: Dwarf Shaman voor de Alliance',
    ],
    traits: { nature: 3, hybrid: 3, heal: 2, magic: 2, melee: 2, ranged: 1, complex: 2, solo: 2, burst: 1 },
    duel: [
      'Je laat bliksem uit de lucht op je vijanden neerslaan.',
      'Je plant totems die je hele groep versterken.',
      'Je praat met de geesten van vuur, aarde, water en lucht.',
      'Je slaat toe met een bijl die knettert van de elektriciteit.',
    ],
  },
  {
    id: 'mage',
    name: 'Mage',
    abbr: 'Mag',
    icon: '🔥',
    color: '#3FC7EB',
    roles: ['ranged'],
    specs: ['Arcane', 'Fire', 'Frost'],
    resource: 'Mana',
    armor: 'Cloth',
    difficulty: 3,
    soloEase: 4,
    tagline: 'Vuur, ijs en pure arcane macht.',
    fantasy:
      'De Mage is de pure caster: enorme schade op afstand, vijanden bevriezen of in een schaap veranderen, en teleporteren door Azeroth. Sterk in AoE-farmen, maar kwetsbaar als je de controle verliest.',
    pros: [
      'Hoge schade en sterke AoE',
      'Eigen eten en drinken toveren, plus teleports en portals',
      'Veel crowd control: Polymorph, Frost Nova',
    ],
    cons: [
      'Kwetsbaar: weinig ruimte voor fouten',
      'Leunt op positionering en kiten',
      'Populaire class: veel concurrentie',
    ],
    forever: [
      'Nieuw: Orc Mage voor de Horde',
      'Krijgt net als elke class nieuwe talenten en een extra 16-punts mijlpaal per talentboom',
    ],
    traits: { ranged: 3, magic: 3, burst: 3, control: 3, complex: 2, solo: 2 },
    duel: [
      'Je verandert je vijand met één spreuk in een schaap.',
      'Je bevriest een hele groep vijanden op hun plek.',
      'Je opent een portaal naar een verre stad.',
      'Je laat een gigantische vuurbal los.',
    ],
  },
  {
    id: 'warlock',
    name: 'Warlock',
    abbr: 'Lock',
    icon: '😈',
    color: '#8788EE',
    text: '#A3A4F5',
    roles: ['ranged'],
    specs: ['Affliction', 'Demonology', 'Destruction'],
    resource: 'Mana (en Soul Shards)',
    armor: 'Cloth',
    difficulty: 3,
    soloEase: 5,
    tagline: 'Demonen dienen jou, vloeken doen de rest.',
    fantasy:
      'De Warlock vecht met vloeken, DoTs en een demonische metgezel. Life Tap en Drain-spreuken maken je erg zelfvoorzienend: samen met de Hunter de sterkste solo-class volgens de gidsen. In Forever een van de classes met de meeste talentwijzigingen.',
    pros: [
      'Uitstekend solo dankzij je demon en DoTs',
      'Veel utility: Healthstones en spelers summonen',
      'Sterk in PvP door Fear en DoTs',
    ],
    cons: [
      'Kwetsbaar in cloth',
      'Het duistere thema is niet voor iedereen',
      'Flinke rework: talenten nog in beweging tijdens de beta',
    ],
    forever: [
      'Een van de grootste talent-reworks: veel nieuwe talenten in alle drie de bomen',
      'Curses krijgen Banes',
      'De Succubus-lijn wordt de Sayaad',
      'Elke talentboom eindigt in een nieuw talent',
      'Nieuw: Troll Warlock',
    ],
    traits: { ranged: 2, magic: 2, dark: 3, pet: 3, solo: 3, control: 2, simple: 2 },
    duel: [
      'Je roept een demon op die jouw bevelen uitvoert.',
      'Je ruilt je eigen leven in voor meer magische kracht.',
      'Je laat je vijand langzaam wegrotten onder je vloeken.',
      'Je trekt de ziel uit een verslagen tegenstander.',
    ],
  },
  {
    id: 'druid',
    name: 'Druid',
    abbr: 'Dru',
    icon: '🌿',
    color: '#FF7C0A',
    roles: ['tank', 'heal', 'melee', 'ranged'],
    specs: ['Balance', 'Feral Combat', 'Restoration'],
    resource: 'Mana, Rage (beer), Energy (kat)',
    armor: 'Leather',
    difficulty: 4,
    soloEase: 4,
    tagline: 'Beer, kat, boom of maanvuur: jij kiest.',
    fantasy:
      'De Druid verandert van gedaante: beer om te tanken, kat voor melee, en in humanoïde vorm of als Moonkin voor heals en spreuken. De meest veelzijdige class van het spel.',
    pros: [
      'Kan alle vier de rollen spelen',
      'Reisvorm, zeehondvorm en stealth in kattenvorm',
      'Sterke heal-over-time spreuken',
    ],
    cons: [
      'Je hebt gear nodig voor meerdere rollen',
      'Van vorm wisselen kost mana',
      'Veelzijdig, maar concurreert per rol met pure classes',
    ],
    forever: [
      'Primal Bite vervangt Mangle als high-threat aanval van de beer (6 s cooldown)',
      'Wild Growth heelt de hele party',
      'Swiftmend laat je HoT staan',
      'Beta-build: Wrath doet ongeveer 50% meer schade en HoTs kunnen critten',
      'Improved Mark of the Wild is baseline',
    ],
    traits: { shapeshift: 3, nature: 3, hybrid: 3, heal: 2, tank: 2, stealth: 1, melee: 1, ranged: 1, solo: 2, magic: 1 },
    duel: [
      'Je verandert in een enorme beer om je vrienden te beschermen.',
      'Je sluipt als panter door de nacht.',
      'Je laat je vrienden langzaam herstellen met natuurmagie.',
      'Je bent beer, kat, zeehond én genezer: je kiest per moment.',
    ],
  },
];

// Tekstkleur: standaard de class-kleur, behalve waar die te weinig contrast heeft.
for (const c of CLASSES) c.text ??= c.color;

const SKYBORNE_LORE =
  'Elfen die afstammen van Highborne-rebellen. Ze sloten een pact met de windgeesten van Skywall, die hun eiland Zephras Isle het elementaire rijk van de lucht in tilden. Eeuwen geleden verdwenen de windgeesten, en nu begint het eiland te haperen.';

const SKYBORNE_SHARED_RACIALS = [
  { name: 'Walk on Air', type: 'actief', text: 'Zweef 10 seconden lang langzaam naar beneden. Geen echte vlucht.' },
  { name: 'Wind Blessed', type: 'passief', text: '+1% haste voor melee, ranged en spreuken.' },
  { name: 'Elemental Insight', type: 'passief', text: '+5% schade tegen Elementals.' },
];

const SKYBORNE_NOTE = 'Vereist de Skyborne Heroic Pack of een hogere editie. Een abonnement alleen is niet genoeg.';

// synergy: hoe goed de racials bij een class passen (0-3).
// Indicatie op basis van de racials en de consensus van beta-gidsen, geen harde ranking.
export const RACES = [
  {
    id: 'human',
    name: 'Human',
    faction: 'alliance',
    icon: '🏰',
    look: ['klassiek'],
    vibe: ['eer', 'avontuur'],
    pvp: 3,
    pvpWhy: 'Will to Survive breekt stuns en Perception ziet stealth: sterk in PvP',
    quest: 1,
    start: 'Northshire Abbey (Elwynn Forest)',
    capital: 'Stormwind',
    lore: 'De veerkrachtige mensen van Stormwind: ridders, priesters en avonturiers die hun koninkrijk keer op keer herbouwen.',
    classes: ['warrior', 'paladin', 'hunter', 'rogue', 'priest', 'mage', 'warlock'],
    newClasses: ['hunter'],
    racials: [
      { name: 'Will to Survive', type: 'actief', text: 'Verwijdert direct alle stuns. 3 min cooldown.' },
      { name: 'Perception', type: 'actief', text: 'Zie vijanden in stealth gedurende 20 seconden.' },
      { name: 'Sword Specialization', type: 'passief', text: 'Extra kritieke kans met (tweehandige) zwaarden. De exacte waarde verschilt per bron.' },
      { name: 'The Human Spirit', type: 'passief', text: '+5% Spirit.' },
    ],
    synergy: { warrior: 3, paladin: 2, hunter: 1, rogue: 3, priest: 2, mage: 2, warlock: 2 },
  },
  {
    id: 'dwarf',
    name: 'Dwarf',
    faction: 'alliance',
    icon: '⛏️',
    look: ['klein', 'stoer'],
    vibe: ['eer', 'techniek', 'avontuur'],
    pvp: 2,
    quest: 2,
    start: 'Coldridge Valley (Dun Morogh)',
    capital: 'Ironforge',
    lore: 'Ontdekkingsreizigers en smeden uit het besneeuwde Ironforge, gek op schatten, bier en archeologie. Nieuw in Forever: Dwarf Shamans, in de lijn van de Wildhammer-stormzangers.',
    classes: ['warrior', 'paladin', 'hunter', 'rogue', 'priest', 'shaman'],
    newClasses: ['shaman'],
    racials: [
      { name: 'Stoneform', type: 'actief', text: 'Verwijdert en blokkeert bloedingen, gif en ziektes en geeft 10% minder fysieke schade, 8 seconden.' },
      { name: 'Find Treasure', type: 'actief', text: 'Spoor schatkisten in de buurt op.' },
      { name: 'Mace Specialization', type: 'passief', text: '+1% kritieke kans met een mace.' },
      { name: 'Big Game Hunter', type: 'passief', text: '+5% schade tegen Beasts.' },
    ],
    synergy: { warrior: 2, paladin: 2, hunter: 3, rogue: 2, priest: 2, shaman: 2 },
  },
  {
    id: 'nightelf',
    name: 'Night Elf',
    faction: 'alliance',
    icon: '🌙',
    look: ['elegant', 'groot'],
    vibe: ['natuur', 'magie'],
    pvp: 2,
    quest: 2,
    start: 'Shadowglen (Teldrassil)',
    capital: 'Darnassus',
    lore: 'Eeuwenoude elfen uit de wouden van Teldrassil, toegewijd aan de maangodin Elune en aan de natuur. Een van de twee rassen zonder nieuwe class in Forever.',
    classes: ['warrior', 'hunter', 'rogue', 'priest', 'druid'],
    newClasses: [],
    racials: [
      { name: "Elune's Light", type: 'actief', text: '+10% kritieke kans met alle spreuken en aanvallen, 15 seconden. 3 min cooldown.' },
      { name: 'Shadowmeld', type: 'actief', text: 'Glip weg in de schaduw zolang je stilstaat. In combat een langere cooldown.' },
      { name: 'Quickness', type: 'passief', text: '+1% dodge en +2% bewegingssnelheid.' },
      { name: 'Wisp Spirit', type: 'passief', text: 'Als geest na je dood +75% bewegingssnelheid.' },
    ],
    synergy: { warrior: 2, hunter: 2, rogue: 3, priest: 2, druid: 3 },
  },
  {
    id: 'gnome',
    name: 'Gnome',
    faction: 'alliance',
    icon: '⚙️',
    look: ['klein', 'schattig'],
    vibe: ['techniek', 'magie'],
    pvp: 3,
    pvpWhy: 'Escape Artist (roots en snares) en Eureka! zijn sterk in PvP',
    quest: 1,
    start: 'Coldridge Valley (Dun Morogh)',
    capital: 'Ironforge (Tinker Town)',
    lore: 'Briljante, kleine uitvinders die hun hoofdstad Gnomeregan kwijtraakten en vanuit Ironforge aan hun comeback werken. Nieuw in Forever: Gnome Priests, die het Licht benaderen als een exacte wetenschap.',
    classes: ['warrior', 'rogue', 'priest', 'mage', 'warlock'],
    newClasses: ['priest'],
    racials: [
      { name: 'Eureka!', type: 'actief', text: 'Je volgende 3 spreuken of vaardigheden kosten minder en doen 10% meer schade of healing.' },
      { name: 'Escape Artist', type: 'actief', text: 'Ontsnap uit roots en snares en wees er kort immuun voor.' },
      { name: 'Expansive Mind', type: 'passief', text: '+5% maximale Mana, Rage of Energy.' },
      { name: 'Engineering Specialization', type: 'passief', text: 'Engineering-gadgets werken betrouwbaarder.' },
    ],
    synergy: { warrior: 2, rogue: 2, priest: 2, mage: 3, warlock: 3 },
  },
  {
    id: 'skyborne-ho',
    name: 'Skyborne (High Order)',
    short: 'Skyborne',
    faction: 'alliance',
    icon: '🪶',
    look: ['elegant'],
    vibe: ['magie', 'avontuur'],
    pvp: 1,
    quest: 2,
    skyborne: true,
    start: 'Zephras Isle (level 1-12)',
    capital: 'Geen eigen hoofdstad; na level 12 door naar de Alliance-zones',
    lore: SKYBORNE_LORE + ' De High Order zijn afstammelingen van Highborne-magisters die onafhankelijkheid zoeken, en kiezen de kant van de Alliance.',
    note: SKYBORNE_NOTE,
    classes: ['warrior', 'hunter', 'rogue', 'druid', 'mage'],
    newClasses: ['warrior', 'hunter', 'rogue', 'druid', 'mage'],
    racials: [
      ...SKYBORNE_SHARED_RACIALS,
      { name: 'Read Ley Line', type: 'actief', text: 'Verdubbelt je health- en mana-regeneratie. Duurt veel langer als er een ley line in de buurt is (exacte duur verschilt per bron).' },
    ],
    synergy: { warrior: 1, hunter: 2, rogue: 1, druid: 2, mage: 2 },
  },
  {
    id: 'orc',
    name: 'Orc',
    faction: 'horde',
    icon: '🪓',
    look: ['groot', 'stoer', 'wild'],
    vibe: ['eer', 'rebel'],
    pvp: 2,
    quest: 1,
    start: 'Valley of Trials (Durotar)',
    capital: 'Orgrimmar',
    lore: 'Trotse krijgers uit Durotar die onder Thrall hun bloeddorstige verleden achter zich lieten en geloven in eer en kracht. Nieuw in Forever: Orc Mages.',
    classes: ['warrior', 'hunter', 'rogue', 'shaman', 'mage', 'warlock'],
    newClasses: ['mage'],
    racials: [
      { name: 'Blood Fury', type: 'actief', text: '+10% attack power en spell power gedurende 15 seconden, zonder de oude heal-straf.' },
      { name: 'Shatter Curse', type: 'actief', text: 'Verwijdert alle Curses en Banes en maakt je er immuun voor; 15% minder magische schade, 8 seconden. 3 min cooldown.' },
      { name: 'Axe Specialization', type: 'passief', text: '+1% kritieke kans met bijlen.' },
      { name: 'Hardiness', type: 'passief', text: 'Stuns duren 20% korter.' },
    ],
    synergy: { warrior: 3, hunter: 3, rogue: 2, shaman: 3, mage: 2, warlock: 3 },
  },
  {
    id: 'undead',
    name: 'Undead',
    faction: 'horde',
    icon: '💀',
    look: ['macaber'],
    vibe: ['rebel', 'duister'],
    pvp: 3,
    pvpWhy: 'Will of the Forsaken breekt Fear, Charm en Sleep: sterk in PvP',
    quest: 2,
    start: 'Deathknell (Tirisfal Glades)',
    capital: 'Undercity',
    lore: 'Bevrijd van de Lich King en geleid door Sylvanas vechten de Forsaken vanuit Undercity voor hun eigen bestaan. Nieuw in Forever: Undead Paladins, die volgens de gidsen rond level 10 bij Bandarion Keep in Tirisfal beginnen en hun plek binnen de Forsaken moeten verdienen.',
    classes: ['warrior', 'paladin', 'rogue', 'priest', 'mage', 'warlock'],
    newClasses: ['paladin'],
    racials: [
      { name: 'Will of the Forsaken', type: 'actief', text: 'Verwijdert direct alle Charm-, Fear- en Sleep-effecten.' },
      { name: 'Cannibalize', type: 'actief', text: 'Eet van een lijk: herstelt in 10 seconden 35% health én (nieuw) 35% mana. Stopt bij bewegen of schade. 2 min cooldown.' },
      { name: 'Underwater Breathing', type: 'passief', text: 'Je kunt 300% langer onder water blijven.' },
      { name: 'Touch of the Grave', type: 'passief', text: 'Kans om bij een treffer health van je doelwit af te tappen. De kans verschilt per bron.' },
    ],
    synergy: { warrior: 2, paladin: 2, rogue: 3, priest: 3, mage: 3, warlock: 3 },
  },
  {
    id: 'tauren',
    name: 'Tauren',
    faction: 'horde',
    icon: '🐂',
    look: ['groot', 'wild'],
    vibe: ['natuur', 'eer'],
    pvp: 2,
    quest: 3,
    start: 'Camp Narache (Mulgore)',
    capital: 'Thunder Bluff',
    lore: 'Vredelievende reuzen uit Mulgore die de Aardmoeder eren, maar onverzettelijk zijn als het op vechten aankomt. Een van de twee rassen zonder nieuwe class in Forever.',
    classes: ['warrior', 'hunter', 'shaman', 'druid'],
    newClasses: [],
    racials: [
      { name: 'War Stomp', type: 'actief', text: 'Stunt vijanden om je heen 2 seconden (0,5 s cast).' },
      { name: 'Cultivation', type: 'actief', text: 'Laat extra kruiden groeien die je ook zonder Herbalism kunt plukken.' },
      { name: 'Plainsrunning', type: 'passief', text: 'Hoe langer je blijft bewegen, hoe sneller je gaat (tot +30% volgens beta-data).' },
      { name: 'Endurance', type: 'passief', text: '+5% health en +1% hit.' },
    ],
    synergy: { warrior: 3, hunter: 2, shaman: 2, druid: 3 },
  },
  {
    id: 'troll',
    name: 'Troll',
    faction: 'horde',
    icon: '🏝️',
    look: ['groot', 'wild'],
    vibe: ['natuur', 'duister', 'magie'],
    pvp: 1,
    quest: 3,
    start: 'Valley of Trials (Durotar)',
    capital: 'Orgrimmar (Valley of Spirits)',
    lore: 'De Darkspear-trollen van de Echo Isles: voodoo, loa-geesten en een verbazingwekkend vermogen om te herstellen. Nieuw in Forever: Troll Warlocks, heksendokters die pacten sluiten met duistere loa.',
    classes: ['warrior', 'hunter', 'rogue', 'priest', 'shaman', 'mage', 'warlock'],
    newClasses: ['warlock'],
    racials: [
      { name: 'Berserking', type: 'actief', text: '+10% aanvals- en castsnelheid, 10 seconden.' },
      { name: 'Rapid Regeneration', type: 'actief', text: 'Herstel 50% van je maximale health tijdens een korte channel (beta: 6 s). Stopt bij actie, beweging of schade.' },
      { name: 'Beast Slaying', type: 'passief', text: '+5% schade tegen Beasts.' },
      { name: 'Regeneration', type: 'passief', text: '10% van je health-regeneratie loopt door in combat.' },
    ],
    synergy: { warrior: 2, hunter: 3, rogue: 2, priest: 2, shaman: 2, mage: 3, warlock: 2 },
  },
  {
    id: 'skyborne-ws',
    name: 'Skyborne (Windshaper)',
    short: 'Skyborne',
    faction: 'horde',
    icon: '🌬️',
    look: ['elegant'],
    vibe: ['natuur', 'avontuur'],
    pvp: 1,
    quest: 2,
    skyborne: true,
    start: 'Zephras Isle (level 1-12)',
    capital: 'Geen eigen hoofdstad; na level 12 door naar de Horde-zones',
    lore: SKYBORNE_LORE + ' De Windshapers zijn de sjamanistische spirituele leiders van de Skyborne, en kiezen de kant van de Horde.',
    note: SKYBORNE_NOTE,
    classes: ['warrior', 'hunter', 'rogue', 'druid', 'shaman'],
    newClasses: ['warrior', 'hunter', 'rogue', 'druid', 'shaman'],
    racials: [
      ...SKYBORNE_SHARED_RACIALS,
      { name: 'Skysight', type: 'actief', text: '+10% loopsnelheid. Duurt veel langer als er een elementaire convergence in de buurt is.' },
    ],
    synergy: { warrior: 1, hunter: 2, rogue: 1, druid: 2, shaman: 2 },
  },
];

export const FACTIONS = {
  alliance: { label: 'Alliance', icon: '🦁' },
  horde: { label: 'Horde', icon: '🐺' },
};

export const classById = Object.fromEntries(CLASSES.map((c) => [c.id, c]));
export const raceById = Object.fromEntries(RACES.map((r) => [r.id, r]));

export function racesForClass(classId) {
  return RACES.filter((r) => r.classes.includes(classId));
}

export function isNewCombo(race, classId) {
  return race.newClasses.includes(classId);
}

export const FACTS = [
  { title: 'Launch', text: `WoW Forever start op ${LAUNCH_DATE} om 15:00 Pacific-tijd; in Nederland is dat 5 november om 00:00. Je speelt het met een gewoon WoW-abonnement of Game Time.` },
  { title: 'Level 60, voor altijd', text: 'De levelcap blijft 60. Geen vliegende mounts en geen level scaling: de reis telt, niet de bestemming.' },
  { title: 'Nieuwe content', text: 'Volgens Blizzard drie nieuwe zones, meer dan 1.000 quests, negen dungeons en twee raids, met o.a. Mount Hyjal en Zephras Isle.' },
  { title: 'Geen realmlijst', text: 'Je kiest bij het maken van je character een ruleset: Normal, PvP of Roleplaying. Je groept alleen met spelers op dezelfde ruleset.' },
  { title: 'PvP-ruleset: één faction', text: 'Op de PvP-ruleset kun je alleen characters van één faction maken. Speel je met vrienden? Spreek dus vooraf af: Alliance of Horde.' },
  { title: 'Hardcore komt later', text: 'Hardcore (één leven) komt na de launch. Gestorven characters kunnen daarna naar een andere ruleset verhuizen.' },
  { title: 'Legacy', text: 'Account-brede Legacy Points (max. 65 bij launch) geven perks en cosmetica. Per character kun je er maximaal 16 besteden.' },
  { title: 'Dual spec', text: 'Vanaf level 40 kun je twee specs tegelijk hebben. Talenten reset je bij een class trainer in een hoofdstad.' },
  { title: 'Talenten', text: 'Elke class houdt drie talentbomen. In totaal zijn er 467 talenten, waarvan ruim honderd nieuw volgens fan-tellingen uit de beta, en er is een nieuwe mijlpaal bij 16 punten.' },
  { title: 'Skyborne', text: 'Het nieuwe ras vereist de Skyborne Heroic Pack of een hogere editie. Controleer de exacte editie in de Blizzard-shop.' },
];

export const SOURCES = [
  { label: 'Icy Veins: officiële race/class-combinaties en racials', url: 'https://www.icy-veins.com/wow-forever/news/all-new-race-and-class-combos-and-racial-abilities-in-wow-forever-official/' },
  { label: 'Icy Veins: WoW Forever Racial Guide', url: 'https://www.icy-veins.com/wow-forever/race-guide' },
  { label: 'Icy Veins: Choosing Your Class', url: 'https://www.icy-veins.com/wow-forever/choosing-your-main' },
  { label: 'Icy Veins: The Skyborne', url: 'https://www.icy-veins.com/wow-forever/skyborne' },
  { label: 'Icy Veins: Realms', url: 'https://www.icy-veins.com/wow-forever/realms' },
  { label: 'Blizzard: Meet the New Skyborne', url: 'http://worldofwarcraft.blizzard.com/en-us/news/24302071/wow-forever-meet-the-new-skyborne' },
  { label: 'Blizzard: Get to Know the Legacy System', url: 'https://news.blizzard.com/en-us/article/24307383/get-to-know-the-world-of-warcraft-forever-legacy-system' },
  { label: 'Method: All New Racial Abilities in WoW Forever', url: 'https://www.method.gg/wow-classic/all-new-racial-abilities-in-world-of-warcraft-forever' },
  { label: 'Warcraft Tavern: WoW Forever aangekondigd op BlizzCon 2026', url: 'https://www.warcrafttavern.com/forever/news/warcraft-forever-classic-announced-at-blizzcon-2026/' },
  { label: 'Warcraft Tavern: Skyborne Racial Abilities', url: 'https://www.warcrafttavern.com/forever/guides/skyborne-racials/' },
  { label: 'Forever Atlas: Race & Class Combinations Chart', url: 'https://wowforeveratlas.com/race-class-combinations' },
  { label: 'Massively OP: BlizzCon 2026 Forever deep dive', url: 'https://massivelyop.com/2026/09/12/blizzcon-2026-world-of-warcraft-forever-deep-dive-promises-adventures-worth-telling-in-the-original-world-of-azeroth/' },
  { label: 'Icy Veins: grootste class-wijzigingen in de Forever-update', url: 'https://www.icy-veins.com/wow-forever/news/the-biggest-class-changes-coming-in-todays-forever-update/' },
];
